#!/bin/bash
if [ -z "$1" ]
  then
    echo "brm [options] <path>"
    echo "  -r delete all folders"
  else 
    if [ "$1" == "-r" ]
      then
    	if [ -z "$2" ]
    	  then
    	   if [ -d "$2" ]
    	     then
         	  find "$2" -type f | while read line; do dd if=/dev/zero of="$line" bs=1k count=2048 && gshred "$line"; done
         	  rm -rf $2
           fi
    	fi   
      else
        if [ -d "$1" ]
         then
          find "$1" -type f | while read line; do dd if=/dev/zero of="$line" bs=1k count=2048 && gshred "$line" && rm "$line"; done
         else
          dd if=/dev/zero of="$1" bs=1k count=2048 && gshred "$1" && rm "$1"
        fi
    fi
fi
