#!/bin/bash
function help {
  echo "badrm <path> | <file>"
}

if [ -z "$1" ]
  then
   help
  else 
        if [ -d "$1" ]
         then
          find "$1" -type f | while read line; do dd if=/dev/zero of="$line" bs=1k count=2048 && gshred "$line" && rm -rf "$line"; done
          rm -rf "$1"
	else if [ -a "$1" ]; then
            dd if=/dev/zero of="$1" bs=1k count=2048 && gshred $(pwd)/"$1" && rm $(pwd)/"$1"
             else
               help
	  fi
        fi
fi
