#!/bin/bash
function help {
	echo "ftar <path/to/dir> [path/to/output]"
}

if [[ ( $# -eq 1 || $# -eq 2 )&& -d "$1" ]]; then
	tar zcf "$1.tar.gz" $1
	if [[ $# -eq 2 && -d "$2" ]]; then
		mv "$1.tar.gz" "$2"
	else
		help
	fi
else
	help
fi