#!/bin/bash
function help {
	echo "ftar <path/to/dir> [path/to/output]"
}

if [[ ( $# -eq 1 || $# -eq 2 )&& -d "$1" ]]; then
	SPATH=$(sed "s/\///g" <<< $1)
	tar zcf "$SPATH.tar.gz" $SPATH
	if [[ $# -eq 2 && -d "$2" ]]; then
		mv "$1.tar.gz" "$2"
	else
		help
	fi
else
	help
fi